targets:
  $default:
    builders:
      drift_dev:
        options:
          skip_verification_code: false
          use_sql_column_name_as_json_key: true
          generate_values_in_copy_with: true
          store_date_time_values_as_text: false
