// Mocks generated by Mockito 5.4.6 from annotations
// in red_letter/test/controllers/review_session_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:drift/drift.dart' as _i3;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:fsrs/fsrs.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:red_letter/data/database/app_database.dart' as _i2;
import 'package:red_letter/data/database/user_progress_dao.dart' as _i7;
import 'package:red_letter/services/fsrs_scheduler_service.dart' as _i10;
import 'package:red_letter/services/working_set_service.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_1 extends _i1.SmartFake
    implements _i3.DatabaseConnection {
  _FakeDatabaseConnection_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_2 extends _i1.SmartFake
    implements _i3.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_3 extends _i1.SmartFake implements _i3.QueryExecutor {
  _FakeQueryExecutor_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_4 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_5 extends _i1.SmartFake
    implements _i3.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$PassagesTable_6 extends _i1.SmartFake
    implements _i2.$PassagesTable {
  _Fake$PassagesTable_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$UserProgressTableTable_7 extends _i1.SmartFake
    implements _i2.$UserProgressTableTable {
  _Fake$UserProgressTableTable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_8<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_9<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.InsertStatement<T1, D1> {
  _FakeInsertStatement_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_10<T extends _i3.Table, D> extends _i1.SmartFake
    implements _i3.UpdateStatement<T, D> {
  _FakeUpdateStatement_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_11<T1 extends _i3.HasResultSet, D>
    extends _i1.SmartFake
    implements _i3.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_12<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i3.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_13<Row> extends _i1.SmartFake
    implements _i3.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_14<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_15<T> extends _i1.SmartFake implements _i3.Selectable<T> {
  _FakeSelectable_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_16 extends _i1.SmartFake
    implements _i3.GenerationContext {
  _FakeGenerationContext_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeScheduler_17 extends _i1.SmartFake implements _i6.Scheduler {
  _FakeScheduler_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProgressTableCompanion_18 extends _i1.SmartFake
    implements _i2.UserProgressTableCompanion {
  _FakeUserProgressTableCompanion_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_19 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserProgressDAO].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProgressDAO extends _i1.Mock implements _i7.UserProgressDAO {
  MockUserProgressDAO() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeAppDatabase_0(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i2.AppDatabase);

  @override
  _i3.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_1(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i3.DatabaseConnection);

  @override
  _i3.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_2(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i3.DriftDatabaseOptions);

  @override
  _i3.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i8.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i3.SqlTypes);

  @override
  _i3.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_3(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i3.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_4(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i4.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_5(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i3.DatabaseConnectionUser);

  @override
  _i2.$PassagesTable get passages =>
      (super.noSuchMethod(
            Invocation.getter(#passages),
            returnValue: _Fake$PassagesTable_6(
              this,
              Invocation.getter(#passages),
            ),
          )
          as _i2.$PassagesTable);

  @override
  _i2.$UserProgressTableTable get userProgressTable =>
      (super.noSuchMethod(
            Invocation.getter(#userProgressTable),
            returnValue: _Fake$UserProgressTableTable_7(
              this,
              Invocation.getter(#userProgressTable),
            ),
          )
          as _i2.$UserProgressTableTable);

  @override
  _i5.Future<_i2.UserProgress?> getProgressByPassageId(String? passageId) =>
      (super.noSuchMethod(
            Invocation.method(#getProgressByPassageId, [passageId]),
            returnValue: _i5.Future<_i2.UserProgress?>.value(),
          )
          as _i5.Future<_i2.UserProgress?>);

  @override
  _i5.Future<List<_i2.UserProgress>> getAllProgress() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProgress, []),
            returnValue: _i5.Future<List<_i2.UserProgress>>.value(
              <_i2.UserProgress>[],
            ),
          )
          as _i5.Future<List<_i2.UserProgress>>);

  @override
  _i5.Future<List<_i2.UserProgress>> getDueForReview() =>
      (super.noSuchMethod(
            Invocation.method(#getDueForReview, []),
            returnValue: _i5.Future<List<_i2.UserProgress>>.value(
              <_i2.UserProgress>[],
            ),
          )
          as _i5.Future<List<_i2.UserProgress>>);

  @override
  _i5.Future<List<_i2.UserProgress>> getNewCards({int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getNewCards, [], {#limit: limit}),
            returnValue: _i5.Future<List<_i2.UserProgress>>.value(
              <_i2.UserProgress>[],
            ),
          )
          as _i5.Future<List<_i2.UserProgress>>);

  @override
  _i5.Future<List<_i2.UserProgress>> getDueReviewCards({int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getDueReviewCards, [], {#limit: limit}),
            returnValue: _i5.Future<List<_i2.UserProgress>>.value(
              <_i2.UserProgress>[],
            ),
          )
          as _i5.Future<List<_i2.UserProgress>>);

  @override
  _i5.Future<List<_i2.UserProgress>> getLearningCards() =>
      (super.noSuchMethod(
            Invocation.method(#getLearningCards, []),
            returnValue: _i5.Future<List<_i2.UserProgress>>.value(
              <_i2.UserProgress>[],
            ),
          )
          as _i5.Future<List<_i2.UserProgress>>);

  @override
  _i5.Future<List<_i2.UserProgress>> getRelearningCards() =>
      (super.noSuchMethod(
            Invocation.method(#getRelearningCards, []),
            returnValue: _i5.Future<List<_i2.UserProgress>>.value(
              <_i2.UserProgress>[],
            ),
          )
          as _i5.Future<List<_i2.UserProgress>>);

  @override
  _i5.Future<List<_i2.UserProgress>> getReviewQueue({int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewQueue, [], {#limit: limit}),
            returnValue: _i5.Future<List<_i2.UserProgress>>.value(
              <_i2.UserProgress>[],
            ),
          )
          as _i5.Future<List<_i2.UserProgress>>);

  @override
  _i5.Future<Map<int, int>> getCardCountsByState() =>
      (super.noSuchMethod(
            Invocation.method(#getCardCountsByState, []),
            returnValue: _i5.Future<Map<int, int>>.value(<int, int>{}),
          )
          as _i5.Future<Map<int, int>>);

  @override
  _i5.Future<List<_i2.UserProgress>> getProgressByMasteryLevel(
    int? masteryLevel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProgressByMasteryLevel, [masteryLevel]),
            returnValue: _i5.Future<List<_i2.UserProgress>>.value(
              <_i2.UserProgress>[],
            ),
          )
          as _i5.Future<List<_i2.UserProgress>>);

  @override
  _i5.Future<Map<int, int>> getMasteryLevelCounts() =>
      (super.noSuchMethod(
            Invocation.method(#getMasteryLevelCounts, []),
            returnValue: _i5.Future<Map<int, int>>.value(<int, int>{}),
          )
          as _i5.Future<Map<int, int>>);

  @override
  _i5.Future<int> createProgress(String? passageId) =>
      (super.noSuchMethod(
            Invocation.method(#createProgress, [passageId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> upsertProgress(_i2.UserProgressTableCompanion? progress) =>
      (super.noSuchMethod(
            Invocation.method(#upsertProgress, [progress]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> updateMasteryLevel(String? passageId, int? masteryLevel) =>
      (super.noSuchMethod(
            Invocation.method(#updateMasteryLevel, [passageId, masteryLevel]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> updateFSRSData({
    required String? passageId,
    required double? stability,
    required double? difficulty,
    required int? step,
    required int? state,
    required DateTime? lastReviewed,
    required DateTime? nextReview,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateFSRSData, [], {
              #passageId: passageId,
              #stability: stability,
              #difficulty: difficulty,
              #step: step,
              #state: state,
              #lastReviewed: lastReviewed,
              #nextReview: nextReview,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> updateSemanticReflection(
    String? passageId,
    String? reflection,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSemanticReflection, [
              passageId,
              reflection,
            ]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> recordReview({
    required String? passageId,
    required int? masteryLevel,
    required double? stability,
    required double? difficulty,
    required int? step,
    required int? state,
    required DateTime? lastReviewed,
    required DateTime? nextReview,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordReview, [], {
              #passageId: passageId,
              #masteryLevel: masteryLevel,
              #stability: stability,
              #difficulty: difficulty,
              #step: step,
              #state: state,
              #lastReviewed: lastReviewed,
              #nextReview: nextReview,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> updateLastSync(String? passageId, DateTime? syncTime) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastSync, [passageId, syncTime]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> deleteProgress(String? passageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProgress, [passageId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> deleteAllProgress() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllProgress, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Stream<T> createStream<T extends Object>(
    _i4.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i5.Stream<T>.empty(),
          )
          as _i5.Stream<T>);

  @override
  T alias<T, D>(_i3.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i8.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<Set<_i3.TableUpdate>> tableUpdates([
    _i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i5.Stream<Set<_i3.TableUpdate>>.empty(),
          )
          as _i5.Stream<Set<_i3.TableUpdate>>);

  @override
  _i5.Future<T> doWhenOpened<T>(
    _i5.FutureOr<T> Function(_i3.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i5.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_9<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
    _i3.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_10<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_11<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_12<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
    Iterable<_i3.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_13<_i3.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_14<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i3.DeleteStatement<T, D>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]),
          )
          as _i5.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_15<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_15<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i5.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> transaction<T>(
    _i5.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<T> exclusively<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> runWithInterceptor<T>(
    _i5.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_16(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_16(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [WorkingSetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkingSetService extends _i1.Mock implements _i9.WorkingSetService {
  MockWorkingSetService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get newCardsPerDay =>
      (super.noSuchMethod(Invocation.getter(#newCardsPerDay), returnValue: 0)
          as int);

  @override
  _i5.Future<List<_i2.UserProgress>> getAvailableNewCards({
    int? overrideLimit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableNewCards, [], {
              #overrideLimit: overrideLimit,
            }),
            returnValue: _i5.Future<List<_i2.UserProgress>>.value(
              <_i2.UserProgress>[],
            ),
          )
          as _i5.Future<List<_i2.UserProgress>>);

  @override
  _i5.Future<bool> canIntroduceMoreNewCards() =>
      (super.noSuchMethod(
            Invocation.method(#canIntroduceMoreNewCards, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> getRemainingNewCardBudget() =>
      (super.noSuchMethod(
            Invocation.method(#getRemainingNewCardBudget, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> getTotalNewCardsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalNewCardsCount, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);
}

/// A class which mocks [FSRSSchedulerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFSRSSchedulerService extends _i1.Mock
    implements _i10.FSRSSchedulerService {
  MockFSRSSchedulerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Scheduler get scheduler =>
      (super.noSuchMethod(
            Invocation.getter(#scheduler),
            returnValue: _FakeScheduler_17(this, Invocation.getter(#scheduler)),
          )
          as _i6.Scheduler);

  @override
  _i2.UserProgressTableCompanion reviewPassage({
    required String? passageId,
    required _i2.UserProgress? progress,
    required _i6.Rating? rating,
    int? customMasteryLevel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reviewPassage, [], {
              #passageId: passageId,
              #progress: progress,
              #rating: rating,
              #customMasteryLevel: customMasteryLevel,
            }),
            returnValue: _FakeUserProgressTableCompanion_18(
              this,
              Invocation.method(#reviewPassage, [], {
                #passageId: passageId,
                #progress: progress,
                #rating: rating,
                #customMasteryLevel: customMasteryLevel,
              }),
            ),
          )
          as _i2.UserProgressTableCompanion);

  @override
  DateTime calculateNextReview({
    required _i2.UserProgress? progress,
    required String? passageId,
    required _i6.Rating? rating,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateNextReview, [], {
              #progress: progress,
              #passageId: passageId,
              #rating: rating,
            }),
            returnValue: _FakeDateTime_19(
              this,
              Invocation.method(#calculateNextReview, [], {
                #progress: progress,
                #passageId: passageId,
                #rating: rating,
              }),
            ),
          )
          as DateTime);

  @override
  double? getRetrievability({
    required _i2.UserProgress? progress,
    required String? passageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRetrievability, [], {
              #progress: progress,
              #passageId: passageId,
            }),
          )
          as double?);

  @override
  Map<_i6.Rating, DateTime> previewNextReviewDates({
    required _i2.UserProgress? progress,
    required String? passageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#previewNextReviewDates, [], {
              #progress: progress,
              #passageId: passageId,
            }),
            returnValue: <_i6.Rating, DateTime>{},
          )
          as Map<_i6.Rating, DateTime>);

  @override
  _i5.Future<_i2.UserProgressTableCompanion> createInitialProgress(
    String? passageId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createInitialProgress, [passageId]),
            returnValue: _i5.Future<_i2.UserProgressTableCompanion>.value(
              _FakeUserProgressTableCompanion_18(
                this,
                Invocation.method(#createInitialProgress, [passageId]),
              ),
            ),
          )
          as _i5.Future<_i2.UserProgressTableCompanion>);
}
